global:
  scrape_interval: 15s  # How often Prometheus scrapes metrics

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: cadvisor
    metrics_path: /metrics
    static_configs:
      - targets: ['transcendence-cadvisor-1:8080']

