# Generated by Django 5.1.4 on 2025-02-20 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_logic_app', '0002_game_ball_dx_game_ball_dy_game_ball_x_game_ball_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games_won', to='game_logic_app.player'),
        ),
    ]
