# Generated by Django 5.1.4 on 2025-02-21 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_logic_app', '0003_game_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='ball_dx',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ball_dy',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ball_x',
        ),
        migrations.RemoveField(
            model_name='game',
            name='ball_y',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player1_y',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player2_y',
        ),
    ]
