# Generated by Django 5.1.4 on 2025-02-22 02:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_logic_app', '0006_remove_game_ball_dx_remove_game_ball_dy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchhistory',
            name='end_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='match_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='matchhistory',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='game_logic_app.tournament'),
        ),
    ]
