global:
  scrape_interval: 15s  # How often Prometheus scrapes metrics
  scrape_timeout: 10s
  evaluation_interval: 15s
rule_files:
  - "first_rules.yml"
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: cadvisor
    metrics_path: /metrics
    static_configs:
      - targets: ['cadvisor_container:8080']

