# Generated by Django 5.1.4 on 2024-12-16 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_blockeduser_chatmessage_ponginvitation_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='ponginvitation',
            name='invitee',
        ),
        migrations.RemoveField(
            model_name='ponginvitation',
            name='inviter',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='BlockedUser',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
        migrations.DeleteModel(
            name='PongInvitation',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
